name: treehack
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy<2.0.0  # Fix numpy version for ultralytics
  - opencv
  - pytorch
  - torchvision
  - jupyterlab
  - pip
  - pip:
      - ultralytics
      - ultralytics-thop>=2.0.0  # Required dependency
      - torch
      - transformers


